[package]
name = "screenshotter"
version = "0.1.0"
edition = "2021"

[dependencies]
charm = { path = "../../", features = ["gtk"] }
gtk = { version = "0.8.2", package = "gtk4" }
tokio = { version = "1.37.0", features = ["sync"] }